### PR TITLE
Restructure packaging

### PR DESCRIPTION
**Pull request by jgru**
Dear Corey, 

this PR fixes a bug in the validity check of mastodon-timestamps, which mistakenly looked at the tiktok-variable (d1d83cd54c214da2c27607524a6f03f6d731a465).
Furthermore, it restructures the packaging to avoid code duplication and to gain flexibility in regard to module usage and script naming. In addition, the help page for the CLI-parameters was made more expressive, while introducing the possibility to decode multiple timestamps of various formats at once. In detail, the following changes were incorporated: 

bdda49843ce8d42dcd1901faaadde3bdd1463d80 adds an explicit main-function to use the script with setuptools' entry_points, which makes the module overally more flexible. This required changing the module-wide variables, which  were set by `locals().update(...)` to be instance variables set by `set_attr(...)`, which is an equally flexible approach.

eae325ac788e5354b422b8e20fd45dafa5fc7400 changes setup.py to install as console_script using entry_points, which brings flexibility in regard to naming the installed script.

65207302fd5f52b2412cb4b80bc249bdc3ad951e removes `time_decode.py` in the top-level directory to avoid code duplication, since this file was previously an exact copy of time_decode/time_decode.py and is not needed anymore.

d187b340dc2bc3cc236f759783cd5b411adb4568 modifies the CLI parameters to be more expressive and to enable the    conversion of multiple timestamps of different formats at once.

Thank you already in advance for considering this PR. 

Best regards
Jan

### CODE REVIEW

**Comment by digitalsleuth** [comment]
Hi Jan,

First of all, good catch on the tiktok/mastodon typo. Second, I like what you've done with the changes with the entry points. I've been meaning to get to that myself but haven't really managed to find the time. I'm going to run a few tests first then if everything works out, I'll merge your PR!

**Comment by digitalsleuth** [comment]
@jgru Thanks again for your effort and changes to enhance this! I'll be pushing a new pip package in the next 24 hours.

**Comment by jgru** [comment]
> @jgru Thanks again for your effort and changes to enhance this! I'll be pushing a new pip package in the next 24 hours.

I am glad that you had nothing to complain about. Looking forward to the upload. Thank you for the review and the merge, @digitalsleuth!

BTW, I think it would be helpful, if you would provide an e-mail-address to contact you.

**Comment by jgru** [comment]
Hi @digitalsleuth, I want to ask, whether you could create an new release 3.1.2, which incorporates the last changes. Would this be possible? Thanks already in advance...

**Pull request merged**
